version: "3.8"

services:
  ##
  # Password manager
  #
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
    volumes:
      - "config:/config/"
      - "data:/data/"
      - "rslsync:/mnt/rslsync_data/:ro"
    networks:
      - proxy
    deploy:
      placement:
        constraints:
          - node.hostname == web
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.http.middlewares.nextcloud-tls.redirectscheme.scheme: "https"

        traefik.http.routers.nextcloud.rule: "Host(`cloud.dejonckhee.re`)"
        traefik.http.routers.nextcloud.entrypoints: "web"
        traefik.http.routers.nextcloud.middlewares: "nextcloud-tls"

        traefik.http.routers.nextcloud-tls.rule: "Host(`cloud.dejonckhee.re`)"
        traefik.http.routers.nextcloud-tls.entrypoints: "websecure"
        traefik.http.routers.nextcloud-tls.tls: "true"
        traefik.http.routers.nextcloud-tls.tls.certresolver: "letsencrypt"

        traefik.http.services.nextcloud.loadbalancer.server.port: "80"
        traefik.docker.network: "traefik_proxy"

volumes:
  config:
  data:
  rslsync:
    name: rslsync_data

networks:
  proxy:
    external: true
    name: "traefik_proxy"
